name: Build CatBrowser Windows EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Compile CatBrowser.exe
      shell: cmd
      run: |
        g++ main.cpp -o CatBrowser.exe -std=c++14 -DWEBVIEW_WINAPI -lole32 -loleaut32 -luuid -lshell32 -lgdi32 -lversion -lcomctl32 -mwindows 2>&1

    - name: Upload Finished Executable
      uses: actions/upload-artifact@v4
      with:
        name: CatBrowser-Windows
        path: |
          CatBrowser.exe
          cathome.html
          sammy.html
          sammy_2.png
